/*
Copyright 2022.

All Rights Reserved
*/
// Code generated by main. DO NOT EDIT.

// +k8s:deepcopy-gen=package
// +groupName=licensing.cattle.io
package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

// EntitlementList is a list of Entitlement resources
type EntitlementList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata"`

	Items []Entitlement `json:"items"`
}

func NewEntitlement(namespace, name string, obj Entitlement) *Entitlement {
	obj.APIVersion, obj.Kind = SchemeGroupVersion.WithKind("Entitlement").ToAPIVersionAndKind()
	obj.Name = name
	obj.Namespace = namespace
	return &obj
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

// RequestList is a list of Request resources
type RequestList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata"`

	Items []Request `json:"items"`
}

func NewRequest(namespace, name string, obj Request) *Request {
	obj.APIVersion, obj.Kind = SchemeGroupVersion.WithKind("Request").ToAPIVersionAndKind()
	obj.Name = name
	obj.Namespace = namespace
	return &obj
}
