/*
Copyright 2022.

All Rights Reserved
*/
// Code generated by main. DO NOT EDIT.

package api

const (
	// Package-wide consts from generator "zz_generated_register".
	GroupName = "licensing.cattle.io"
)
